// <auto-generated />
namespace CMPSAdvising.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CMPSAdvising11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CMPSAdvising11));
        
        string IMigrationMetadata.Id
        {
            get { return "201503010301479_CMPSAdvising11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
